<!-- Js Plugins -->
<script src="<?= base_url('/asset/template/ashion-master/') ?>js/jquery-3.3.1.min.js"></script>
<script src="<?= base_url('/asset/template/ashion-master/') ?>js/bootstrap.min.js"></script>
<script src="<?= base_url('/asset/template/ashion-master/') ?>js/jquery.magnific-popup.min.js"></script>
<script src="<?= base_url('/asset/template/ashion-master/') ?>js/jquery-ui.min.js"></script>
<script src="<?= base_url('/asset/template/ashion-master/') ?>js/mixitup.min.js"></script>
<script src="<?= base_url('/asset/template/ashion-master/') ?>js/jquery.countdown.min.js"></script>
<script src="<?= base_url('/asset/template/ashion-master/') ?>js/jquery.slicknav.js"></script>
<script src="<?= base_url('/asset/template/ashion-master/') ?>js/owl.carousel.min.js"></script>
<script src="<?= base_url('/asset/template/ashion-master/') ?>js/jquery.nicescroll.min.js"></script>
<script src="<?= base_url('/asset/template/ashion-master/') ?>js/main.js"></script>
