<div class="card">
	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			width: 100%;
		}

		.card {
			margin: 0;
			padding: 0;
		}

		.container {
			margin: 0;
			padding: 0;
			width: 100%;
		}

		img {
			max-width: 100%;
			height: auto;
		}

		.card-header {
			width: 100%;
		}

		nav ul {
			list-style: none;
			padding: 0;
			margin: 0;
			display: flex;
		}

		nav ul li {
			margin-right: 10px;
		}

		#example{
			margin-top: 20px;
		}
	</style>
	<div class="card-header">
		<div class="container">
			<div id="branding">
				<h1>Dokumentasi Kelas Audio</h1>
			</div>
			<nav>
				<ul>
					<li><a href="#description">Deskripsi</a></li>
					<li><a href="#usage">Penggunaan</a></li>
					<li><a href="#methods">Metode</a></li>
					<li><a href="#tampilan">Tampilan</a></li>
					<li><a href="#example">Syntax</a></li>
				</ul>
			</nav>
		</div>
	</div>
	<section id="main">
		<article id="description">
			<h2>Deskripsi</h2>
			<p>Kelas <code>JavaRemidi</code> menyediakan aplikasi GUI sederhana yang memutar dan menghentikan file audio
				menggunakan framework Swing Java dan Java Sound API. Kelas ini memperluas <code>javax.swing.JFrame</code>
				dan menggunakan <code>javax.sound.sampled.Clip</code> untuk menangani pemutaran audio.</p>
		</article>

		<article id="usage">
			<h2>Penggunaan</h2>
			<p>Untuk menggunakan kelas <code>KelasAudio</code>, cukup buat instance dari kelas ini dan setel untuk menjadi
				terlihat. Kelas ini menyertakan sebuah tombol untuk memutar dan menghentikan audio, serta sebuah label untuk
				menampilkan gambar.</p>
		</article>

		<article id="methods">
			<h2>Metode</h2>
			<h5>Konstruktor</h5>
			<ul>
				<li><code>JavaRemidi()</code>: Menginisialisasi komponen GUI dan menyiapkan tombol play.</li>
			</ul>

			<h5>Metode Privat</h5>
			<ul>
				<li><code>void initComponents()</code>: Menyiapkan tata letak dan komponen GUI.</li>
				<li><code>void jButton1ActionPerformed(java.awt.event.ActionEvent evt)</code>: Menangani event klik tombol
					play/stop untuk memutar atau menghentikan audio.</li>
			</ul>
		</article>

		<article id="tampilan" class="mb-2">
			<h2>Tampilan</h2>
			<img src="<?= base_url('/asset/components/image/screenshotJava.png') ?>" style="width: 40%; height:40%;">
		</article>

		<article id="example">
			<h2>Syntax</h2>
			<p>Kode berikut menunjukkan cara membuat dan menampilkan form <code>JavaRemidi</code>:</p>
			<pre>
				<code>
					/*
					* To change this license header, choose License Headers in Project Properties.
					* To change this template file, choose Tools | Templates
					* and open the template in the editor.
					*/
					package javaapplication6;

					import java.io.File;
					import java.io.IOException;
					import javax.sound.sampled.*;

					/**
					*
					* @author user
					*/
					public class JavaRemidi extends javax.swing.JFrame {

					private Clip clip;

					/**
					* Creates new form JavaRemidi
					*/
					public JavaRemidi() {
					initComponents();
					initializeAudio();
					}

					private void initializeAudio() {
					try {
					// Ganti "path/to/your/audio/file.wav" dengan lokasi file WAV Anda
					File audioFile = new File("D:\\File Hasil Extract\\wav\\I Love You So.wav");
					AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
					clip = AudioSystem.getClip();
					clip.open(audioStream);
					} catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
					ex.printStackTrace();
					}
					}

					/**
					* This method is called from within the constructor to initialize the form.
					* WARNING: Do NOT modify this code. The content of this method is always
					* regenerated by the Form Editor.
					*/
					@SuppressWarnings("unchecked")
					// <editor-fold defaultstate="collapsed" desc="Generated Code">
						private void initComponents() {

						jPanel1 = new javax.swing.JPanel();
						jButton2 = new javax.swing.JButton();
						jButton1 = new javax.swing.JButton();
						jLabel1 = new javax.swing.JLabel();
						jLabel2 = new javax.swing.JLabel();

						setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

						jPanel1.setBackground(new java.awt.Color(0, 0, 0));

						jButton2.setBackground(new java.awt.Color(255, 0, 51));
						jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
						jButton2.setText("Pause");
						jButton2.addActionListener(new java.awt.event.ActionListener() {
						public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton2ActionPerformed(evt);
						}
						});

						jButton1.setBackground(new java.awt.Color(0, 204, 0));
						jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
						jButton1.setText("Play");
						jButton1.addActionListener(new java.awt.event.ActionListener() {
						public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton1ActionPerformed(evt);
						}
						});

						jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
						jLabel2.setForeground(new java.awt.Color(102, 102, 255));
						jLabel2.setText("Label");

						javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
						jPanel1.setLayout(jPanel1Layout);
						jPanel1Layout.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel1)
						.addGap(67, 67, 67))
						.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(45, 45, 45)
						.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
						.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(49, 49, 49))
						.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(153, 153, 153)
						.addComponent(jLabel2)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						);
						jPanel1Layout.setVerticalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1)
						.addGap(26, 26, 26)
						.addComponent(jLabel2)
						.addGap(88, 88, 88)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(46, Short.MAX_VALUE))
						);

						javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
						getContentPane().setLayout(layout);
						layout.setHorizontalGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						);
						layout.setVerticalGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						);

						pack();
						}// </editor-fold>

					private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
					// TODO add your handling code here:
					clip.stop();
					}

					private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
					// TODO add your handling code here:
					// if (clip.isRunning()) {
					// clip.stop();
					// } else {
					// clip.start();
					// }
					clip.start();
					}

					/**
					* @param args the command line arguments
					*/
					public static void main(String args[]) {
					/* Set the Nimbus look and feel */
					//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
						/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
						* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
						*/
						try {
						for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
						if ("Nimbus".equals(info.getName())) {
						javax.swing.UIManager.setLookAndFeel(info.getClassName());
						break;
						}
						}
						} catch (ClassNotFoundException ex) {
						java.util.logging.Logger.getLogger(JavaRemidi.class.getName()).log(java.util.logging.Level.SEVERE, null,
						ex);
						} catch (InstantiationException ex) {
						java.util.logging.Logger.getLogger(JavaRemidi.class.getName()).log(java.util.logging.Level.SEVERE, null,
						ex);
						} catch (IllegalAccessException ex) {
						java.util.logging.Logger.getLogger(JavaRemidi.class.getName()).log(java.util.logging.Level.SEVERE, null,
						ex);
						} catch (javax.swing.UnsupportedLookAndFeelException ex) {
						java.util.logging.Logger.getLogger(JavaRemidi.class.getName()).log(java.util.logging.Level.SEVERE, null,
						ex);
						}
						//</editor-fold>

					/* Create and display the form */
					java.awt.EventQueue.invokeLater(new Runnable() {
					public void run() {
					new JavaRemidi().setVisible(true);
					}
					});
					}

					// Variables declaration - do not modify
					private javax.swing.JButton jButton1;
					private javax.swing.JButton jButton2;
					private javax.swing.JLabel jLabel1;
					private javax.swing.JLabel jLabel2;
					private javax.swing.JPanel jPanel1;
					// End of variables declaration
					}

				</code>
			</pre>
		</article>
	</section>
</div>
